version: "3.3"
services:

  backend:
    build:
      context: .
      dockerfile: deployment/backend.dockerfile
    volumes:
      - ../celery_test:/app
    ports:
      - "8000:8000"
    container_name: backend-server
    depends_on:
      - worker
      - redis
    restart: always

  redis:
    image: redis:3.2
    container_name: redis-server
    ports:
      - "6379:6399"
    restart: always

  worker:
    build:
      context: .
      dockerfile: deployment/worker.dockerfile
    volumes:
      - ../celery_test:/app
    container_name: wroker-server
    depends_on:
      - redis
    restart: always

  flower:
    image: mher/flower
    command:
      - "--broker=redis://redis:6379/0"
    container_name: flower-server
    depends_on:
      - worker
      - redis
    ports:
      - "5555:5555"